<?php

namespace App\Tests\Sync;

use CeculaSyncApiClient\SyncCall;
use \Exception;
use PHPUnit\Framework\TestCase;

final class SyncCallTest extends TestCase
{
    private $syncCall;

    protected function setUp(): void
    {
//        parent::setUp(); // TODO: Change the autogenerated stub
        $this->syncCall = new SyncCall();
    }

    /**
     * @param $mobile
     * @test
     * @dataProvider supplyNumbers
     * @throws Exception
     */
    public function dialMethodThrowsExceptionWhenNumberIsInvalid($mobile): void
    {
        self::expectException(Exception::class);
        self::expectExceptionCode(100);
        $this->syncCall->dial($mobile);
    }


    public function supplyNumbers(): array
    {
        return [
            ["234818317277012"],
            ["234818317277013"],
            ["23481831727701"],
            ["hello"]
        ];
    }

    /**
     * @test
     */
    public function dialMethodThrowsExceptionWhenNumberIsNotProvided(): void
    {
        self::expectException(Exception::class);
        self::expectExceptionCode(404);
        $this->syncCall->dial("");
    }

}